name: 'Terraform Deployment'
run-name: ${{github.actor}} deploying Terraform
on:
  pull_request:
    branches:
      - 'master'
    paths:
        - 'terraform/**'

env:
  TF_VAR_project_id: ${{ secrets.PROJECT_ID }}
  TF_VAR_region: 'us-central1'
  GOOGLE_APPLICATION_CREDENTIALS: ${{github.workspace}}/gcp-credentials.json
  TF_VAR_gcp_credentials: ${{github.workspace}}/gcp-credentials.json

jobs:
  terraform:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Move to Terraform Directory
      run: cd terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7
    - name: Authenticate with GCP
      run: |
        echo '${{ secrets.GCP_CREDENTIAL }}' > gcp-credentials.json
        gcloud auth activate-service-account --key-file=gcp-credentials.json
    
    - name: Terraform Init
      run: |
        cd terraform
        terraform init

    - name: Terraform Format Check
      run: |
        cd terraform
        terraform fmt

    - name: Terraform Validate
      run: |
        cd terraform
        terraform validate

    - name: Terraform Plan
      run: |
        cd terraform
        terraform plan -out=tfplan -input=false
    
    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: terraform/tfplan


    - run: |
        echo 'Terraform Plan Complete'
  
